 requireLazy(["__bigPipe"], function (bigPipe) {
                bigPipe.onPageletArrive({
                    displayResources: ["VC6Dj0h", "DvIsx5X", "6qUA1gl", "lUg7w0b", "hZeK99e", "PDQbV7k", "M7ZJk4o", "pDmmboz", "Gd5GBLJ"],
                    id: "first_response",
                    phase: 0,
                    last_in_phase: true,
                    tti_phase: 0,
                    all_phases: [63, 7],
                    jsmods: {
                        define: [
                            ["CookieDomain", [], { domain: "facebook.com" }, 6421],
                            [
                                "CookieCoreConfig",
                                [],
                                {
                                    c_user: {},
                                    cppo: { t: 86400 },
                                    dpr: { t: 604800 },
                                    fbl_ci: { t: 31536000 },
                                    fbl_cs: { t: 31536000 },
                                    fbl_st: { t: 31536000 },
                                    i_user: {},
                                    locale: { t: 604800 },
                                    m_ls: { t: 158284800 },
                                    m_pixel_ratio: { t: 604800 },
                                    noscript: {},
                                    presence: { t: 2592000 },
                                    sfau: {},
                                    usida: {},
                                    vpd: { t: 5184000 },
                                    wd: { t: 604800 },
                                    wl_cbv: { t: 7776000 },
                                    "x-referer": {},
                                    "x-src": { t: 1 },
                                },
                                2104,
                            ],
                            ["CookieCoreLoggingConfig", [], { maximumIgnorableStallMs: 16.67, sampleRate: 9.7e-5, sampleRateClassic: 1.0e-10, sampleRateFastStale: 1.0e-8 }, 3401],
                            ["ServerTimeData", [], { serverTime: 1686212963402, timeOfRequestStart: 1686212963263.5, timeOfResponseStart: 1686212963263.5 }, 5943],
                            ["IntlVariationHoldout", [], { disable_variation: false }, 6533],
                            ["IntlNumberTypeProps", ["IntlCLDRNumberType05"], { module: { __m: "IntlCLDRNumberType05" } }, 7027],
                            ["FbtResultGK", [], { shouldReturnFbtResult: true, inlineMode: "NO_INLINE" }, 876],
                            [
                                "IntlPhonologicalRules",
                                [],
                                { meta: { "/_B/": "([.,!?\\s]|^)", "/_E/": "([.,!?\\s]|$)" }, patterns: { "/\u0001(.*)('|&#039;)s\u0001(?:'|&#039;)s(.*)/": "\u0001$1$2s\u0001$3", "/_\u0001([^\u0001]*)\u0001/": "javascript" } },
                                1496,
                            ],
                            ["IntlViewerContext", [], { GENDER: 3, regionalLocale: null }, 772],
                            [
                                "MJSEnvironment",
                                [],
                                {
                                    IS_APPLE_WEBKIT_IOS: false,
                                    IS_TABLET: false,
                                    IS_ANDROID: false,
                                    IS_CHROME: false,
                                    IS_FIREFOX: true,
                                    IS_WINDOWS_PHONE: false,
                                    IS_SAMSUNG_DEVICE: false,
                                    OS_VERSION: 2.5,
                                    PIXEL_RATIO: 1,
                                    BROWSER_NAME: "Firefox Mobile",
                                },
                                46,
                            ],
                            ["MLoadingIndicatorSigils", [], { ANIMATE: "m-loading-indicator-animate", ROOT: "m-loading-indicator-root" }, 279],
                            [
                                "NumberFormatConfig",
                                [],
                                { decimalSeparator: ".", numberDelimiter: ",", minDigitsForThousandsSeparator: 4, standardDecimalPatternInfo: { primaryGroupSize: 3, secondaryGroupSize: 3 }, numberingSystemData: null },
                                54,
                            ],
                            [
                                "UserAgentData",
                                [],
                                {
                                    browserArchitecture: "32",
                                    browserFullVersion: "2.5",
                                    browserMinorVersion: 5,
                                    browserName: "KaiOS",
                                    browserVersion: 2,
                                    deviceName: "Unknown",
                                    engineName: "Gecko",
                                    engineVersion: "48.0",
                                    platformArchitecture: "32",
                                    platformName: "KaiOS",
                                    platformVersion: "2.5",
                                    platformFullVersion: "2.5",
                                },
                                527,
                            ],
                            ["ZeroCategoryHeader", [], {}, 1127],
                            [
                                "ZeroRewriteRules",
                                [],
                                {
                                    rewrite_rules: { m: "m", mobile: "m" },
                                    whitelist: {
                                        "/hr/r": 1,
                                        "/hr/p": 1,
                                        "/zero/unsupported_browser/": 1,
                                        "/zero/policy/optin": 1,
                                        "/zero/optin/write/": 1,
                                        "/zero/optin/legal/": 1,
                                        "/zero/optin/free/": 1,
                                        "/about/privacy/": 1,
                                        "/about/privacy/update/": 1,
                                        "/privacy/explanation/": 1,
                                        "/zero/toggle/welcome/": 1,
                                        "/zero/toggle/nux/": 1,
                                        "/zero/toggle/settings/": 1,
                                        "/fup/interstitial/": 1,
                                        "/work/landing": 1,
                                        "/work/login/": 1,
                                        "/work/email/": 1,
                                        "/ai.php": 1,
                                        "/js_dialog_resources/dialog_descriptions_android.json": 0,
                                        "/connect/jsdialog/MPlatformAppInvitesJSDialog/": 0,
                                        "/connect/jsdialog/MPlatformOAuthShimJSDialog/": 0,
                                        "/connect/jsdialog/MPlatformLikeJSDialog/": 0,
                                        "/qp/interstitial/": 1,
                                        "/qp/action/redirect/": 1,
                                        "/qp/action/close/": 1,
                                        "/zero/support/ineligible/": 1,
                                        "/zero_balance_redirect/": 1,
                                        "/zero_balance_redirect": 1,
                                        "/zero_balance_redirect/l/": 1,
                                        "/l.php": 1,
                                        "/lsr.php": 1,
                                        "/ajax/dtsg/": 1,
                                        "/checkpoint/block/": 1,
                                        "/exitdsite": 1,
                                        "/zero/balance/pixel/": 1,
                                        "/zero/balance/": 1,
                                        "/zero/balance/carrier_landing/": 1,
                                        "/zero/flex/logging/": 1,
                                        "/tr": 1,
                                        "/tr/": 1,
                                        "/sem_campaigns/sem_pixel_test/": 1,
                                        "/bookmarks/flyout/body/": 1,
                                        "/zero/subno/": 1,
                                        "/confirmemail.php": 1,
                                        "/policies/": 1,
                                        "/mobile/internetdotorg/classifier/": 1,
                                        "/zero/dogfooding": 1,
                                        "/xti.php": 1,
                                        "/zero/fblite/config/": 1,
                                        "/hr/zsh/wc/": 1,
                                        "/ajax/bootloader-endpoint/": 1,
                                        "/mobile/zero/carrier_page/": 1,
                                        "/mobile/zero/carrier_page/education_page/": 1,
                                        "/mobile/zero/carrier_page/feature_switch/": 1,
                                        "/mobile/zero/carrier_page/settings_page/": 1,
                                        "/aloha_check_build": 1,
                                        "/upsell/zbd/softnudge/": 1,
                                        "/mobile/zero/af_transition/": 1,
                                        "/mobile/zero/af_transition/action/": 1,
                                        "/mobile/zero/freemium/": 1,
                                        "/mobile/zero/freemium/redirect/": 1,
                                        "/mobile/zero/freemium/zero_fup/": 1,
                                        "/privacy/policy/": 1,
                                        "/privacy/center/": 1,
                                        "/data/manifest/": 1,
                                        "/4oh4.php": 1,
                                        "/autologin.php": 1,
                                        "/birthday_help.php": 1,
                                        "/checkpoint/": 1,
                                        "/contact-importer/": 1,
                                        "/cr.php": 1,
                                        "/legal/terms/": 1,
                                        "/login.php": 1,
                                        "/login/": 1,
                                        "/mobile/account/": 1,
                                        "/n/": 1,
                                        "/remote_test_device/": 1,
                                        "/upsell/buy/": 1,
                                        "/upsell/buyconfirm/": 1,
                                        "/upsell/buyresult/": 1,
                                        "/upsell/promos/": 1,
                                        "/upsell/continue/": 1,
                                        "/upsell/h/promos/": 1,
                                        "/upsell/loan/learnmore/": 1,
                                        "/upsell/purchase/": 1,
                                        "/upsell/promos/upgrade/": 1,
                                        "/upsell/buy_redirect/": 1,
                                        "/upsell/loan/buyconfirm/": 1,
                                        "/upsell/loan/buy/": 1,
                                        "/upsell/sms/": 1,
                                        "/wap/a/channel/reconnect.php": 1,
                                        "/wap/a/nux/wizard/nav.php": 1,
                                        "/wap/appreg.php": 1,
                                        "/wap/birthday_help.php": 1,
                                        "/wap/c.php": 1,
                                        "/wap/confirmemail.php": 1,
                                        "/wap/cr.php": 1,
                                        "/wap/login.php": 1,
                                        "/wap/r.php": 1,
                                        "/zero/datapolicy": 1,
                                        "/a/timezone.php": 1,
                                        "/a/bz": 1,
                                        "/bz/reliability": 1,
                                        "/r.php": 1,
                                        "/mr/": 1,
                                        "/reg/": 1,
                                        "/registration/log/": 1,
                                        "/terms/": 1,
                                        "/f123/": 1,
                                        "/expert/": 1,
                                        "/experts/": 1,
                                        "/terms/index.php": 1,
                                        "/terms.php": 1,
                                        "/srr/": 1,
                                        "/msite/redirect/": 1,
                                        "/fbs/pixel/": 1,
                                        "/contactpoint/preconfirmation/": 1,
                                        "/contactpoint/cliff/": 1,
                                        "/contactpoint/confirm/submit/": 1,
                                        "/contactpoint/confirmed/": 1,
                                        "/contactpoint/login/": 1,
                                        "/preconfirmation/contactpoint_change/": 1,
                                        "/help/contact/": 1,
                                        "/survey/": 1,
                                        "/upsell/loyaltytopup/accept/": 1,
                                        "/settings/": 1,
                                        "/lite/": 1,
                                        "/zero_status_update/": 1,
                                        "/operator_store/": 1,
                                        "/upsell/": 1,
                                        "/wifiauth/login/": 1,
                                    },
                                },
                                1478,
                            ],
                            [
                                "MobileAppDetect",
                                [],
                                {
                                    is_mobile_app: false,
                                    is_ads_manager_app: false,
                                    is_pages_manager: false,
                                    is_facebook_for_android: false,
                                    is_facebook_for_android_in_app_browser: false,
                                    is_android_faceweb: false,
                                    is_facebook_for_ios: false,
                                    is_instagram: false,
                                    is_messenger_for_android: false,
                                    is_messenger_for_ios: false,
                                    is_messenger_lite_for_android: false,
                                    is_messenger_lite_for_ios: false,
                                    is_wilde: false,
                                    is_kaios: true,
                                    is_whatsapp_smb: false,
                                    is_whatsapp_smb_for_android: false,
                                    is_whatsapp_smb_for_ios: false,
                                },
                                1109,
                            ],
                            [
                                "MWebStorageMonsterWhiteList",
                                [],
                                {
                                    whitelist: [
                                        "^CacheStorageVersion$",
                                        "^RTC_VIDEO_INPUT$",
                                        "^RTC_AUDIO_INPUT$",
                                        "^RTC_AUDIO_OUTPUT$",
                                        "^RTC_IS_AUDIO_ONLY$",
                                        "^RTC_NOISE_SUPPRESSION$",
                                        "^RTC_MUTE_STATE$",
                                        "^Session$",
                                        "^_oz_",
                                        "^_video_bandwidthEstimate$",
                                        "^Banzai$",
                                        "^bz",
                                        "^banzai\\:last_storage_flush$",
                                        "^falco_queue_",
                                        "^mutex",
                                        "^msys",
                                        "^Bandicoot\\:",
                                        "^imp_seq_num$",
                                        "^qe_switcher_nub_selection$",
                                        "^TabId$",
                                        "^sp_pi$",
                                        "^\\:userchooser\\:osessusers$",
                                        "^\\:userchooser\\:settings$",
                                        "^brands\\:console\\:config$",
                                        "^consoleEnabled$",
                                        "^__fb_messenger_desktop_presence_info$",
                                        "^vc_",
                                        "^_showMDevConsole$",
                                        "^ga_client_id$",
                                        "^_mswam_$",
                                        "^am_recently_used_filters\\:",
                                        "^am_image_size_cache$",
                                        "^ickt$",
                                        "^hb_timestamp$",
                                        "^signal_flush_timestamp$",
                                        "^__MWCMAutoJoinNotifNuxBanner\\.showBanner__$",
                                        "^last_fast_refresh$",
                                        "^_ctv_access_token$",
                                        "^_ctv_android_device_info$",
                                        "^_ctv_cast_access_token$",
                                        "^_ctv_casting_remote$",
                                        "^_ctv_console_log_viewer_on_full_screen_player_enabled$",
                                        "^_ctv_cookie_consent_displayed$",
                                        "^_ctv_debug_redux_logger_enabled$",
                                        "^_ctv_deviceUniqueIDFallback$",
                                        "^_ctv_gaming_consent_displayed$",
                                        "^_ctv_installed_app_player_debug_overlay_enabled$",
                                        "^_ctv_last_load_time_ms$",
                                        "^_ctv_locale$",
                                        "^_ctv_logged_out_constraints_sessions_count$",
                                        "^_ctv_reloadedDueToStaleApp$",
                                        "^_ctv_reloadedDueToUnrecoverableError$",
                                        "^_ctv_search_terms$",
                                        "^_ctv_tv_experiments$",
                                        "^_ctv_usedCloseAppFallback$",
                                        "^_ctv_user_sessions$",
                                        "^_ctv_video_debug_overlay_enabled$",
                                        "^_ctv_debug_rampart_server_number$",
                                        "^fx_did$",
                                        "^wa_lang_banner_dismissed$",
                                        "^bulletin_article_reader_onload_dialog_seen$",
                                        "^bulletin_session_attributes$",
                                        "^md_survey$",
                                        "^support_guest_chat$",
                                        "^comet_is_recent_profile_switch$",
                                        "^comet_console_position$",
                                        "^mw_exchange_vm$",
                                        "^has_seen_email_login_toast$",
                                        "^cs_chat_support_user$",
                                        "^NFT_DEVICE_KEY_PRIVATE_V1$",
                                        "^NFT_DEVICE_KEY_PUBLIC_V1$",
                                        "^show_wa_auth_button$",
                                        "^BusinessInbox\\:sortMethod$",
                                        "^LeadsCenter\\:ViewType$",
                                        "^Routing\\:url\\:AdsTALRouting$",
                                        "^BizWebDirectResponseAdsBannerView$",
                                        "^firefly_auth_tokens$",
                                        "^BizWebStoryInsightsOptInBannerView$",
                                    ],
                                },
                                254,
                            ],
                            ["MemoryLoggerConfigWebSitevarConfig", [], { measurement_interval_minutes: 5 }, 5573],
                            ["FWLoader", [], {}, 278],
                            ["ImmediateActiveSecondsConfig", [], { sampling_rate: 0 }, 423],
                            ["MPageControllerGating", [], { shouldDeferUntilCertainNoRedirect: false, shouldReleaseFetcherLock: true, shouldLoadingScreenSetScriptPath: false, shouldRenderAsync404: false }, 2023],
                            [
                                "AnalyticsCoreData",
                                [],
                                {
                                    device_id: "$^|AcbEX4bFTc5DKlJQ7PfaTq53ivLX_cGTEJohRNIzZdHYr7sF30bf9OUggCEv2dStC5w2PH7-_H8ydg30LuH-Yv2sDknKlvU|fd.AcY7LjaplZRgkFx99cjreuW2apbH7oOemtpe234vmpnj1d6VkxBNDYNLGTmDc2xesu-8kehq1MlygT8tFJjw2kjY",
                                    app_id: "412378670482",
                                    enable_bladerunner: false,
                                    enable_ack: true,
                                    push_phase: "C3",
                                    enable_observer: false,
                                    enable_dataloss_timer: false,
                                    enable_fallback_for_br: true,
                                    queue_activation_experiment: false,
                                    max_delay_br_queue: 60000,
                                    max_delay_br_queue_immediate: 3,
                                    consents: {},
                                    app_universe: 1,
                                    br_stateful_batching_exp: true,
                                    enable_br_stateful_batching: false,
                                },
                                5237,
                            ],
                            ["FbtQTOverrides", [], { overrides: {} }, 551],
                            ["cr:1642797", ["BanzaiBase"], { __rc: ["BanzaiBase", "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:694370", ["requestIdleCallbackBlue"], { __rc: ["requestIdleCallbackBlue", "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:692209", ["cancelIdleCallbackBlue"], { __rc: ["cancelIdleCallbackBlue", "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            [
                                "MBanzaiConfig",
                                [],
                                {
                                    MAX_SIZE: 10000,
                                    MAX_WAIT: 30000,
                                    MIN_WAIT: null,
                                    RESTORE_WAIT: 30000,
                                    blacklist: ["time_spent"],
                                    disabled: false,
                                    gks: { platform_oauth_client_events: true, boosted_pagelikes: true },
                                    known_routes: [
                                        "artillery_javascript_actions",
                                        "artillery_javascript_trace",
                                        "artillery_logger_data",
                                        "logger",
                                        "falco",
                                        "gk2_exposure",
                                        "js_error_logging",
                                        "loom_trace",
                                        "marauder",
                                        "perfx_custom_logger_endpoint",
                                        "qex",
                                        "require_cond_exposure_logging",
                                    ],
                                    should_drop_unknown_routes: true,
                                    should_log_unknown_routes: false,
                                },
                                32,
                            ],
                        ],
                        elements: [
                            ["__elem_de5177dd_0_0_++", "u_0_0_Cs", 1],
                            ["__elem_921b58ef_0_0_9P", "login_form", 2],
                            ["__elem_df6b4e4f_0_0_oy", "header_transparency_tooltip", 1],
                            ["__elem_e24cb174_0_0_su", "m_login_password", 1],
                            ["__elem_7216e2ae_0_2_8N", "u_0_1_78", 1],
                            ["__elem_e03291d5_0_1_YW", "u_0_2_/C", 1],
                            ["__elem_e03291d5_0_0_NV", "u_0_3_mN", 1],
                            ["__elem_7216e2ae_0_0_eT", "login_password_step_element", 1],
                            ["__elem_8a020238_0_0_Ep", "forgot-password-link", 1],
                            ["__elem_7216e2ae_0_1_Cz", "signup_button_area", 1],
                            ["__elem_e980dec4_0_0_gd", "signup-button", 1],
                            ["__elem_49f6b607_0_0_Ow", "root", 1],
                            ["__elem_717bb1ae_0_0_yP", "u_0_4_3v", 3],
                            ["__elem_ad2bcfb1_0_0_l8", "u_0_5_1U", 1],
                            ["__elem_eed16c0a_0_0_4X", "u_0_6_Nb", 1],
                            ["__elem_a588f507_0_0_aP", "u_0_7_VI", 1],
                            ["__elem_a588f507_0_1_4W", "u_0_8_8h", 1],
                            ["__elem_0cdc66ad_0_0_AE", "u_0_a_kK", 1],
                            ["__elem_0cdc66ad_0_1_B4", "u_0_b_kF", 1],
                        ],
                        require: [
                            [
                                "MobileZeroRewriteURL",
                                "main",
                                [],
                                [
                                    {
                                        regex_matcher: [
                                            "^(https?)://(api|api2|z-m-api|api-read|z-p3-api|z-p4-api|b-api)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?:/method/user\\.registerPushCallback|/method/user\\.confirmContactpointPreconfirmation|/method/xconfig\\.fetch|/method/mobile\\.gatekeepers|/method/user\\.unregisterPushCallback|/method/notifications\\.get|/me/notification_seen_states|/method/auth\\.expireSession|/method/auth\\.login|/method/bookmarks\\.get|/me/messenger_only_account_migrations|/method/mobile\\.zeroHeaderRequest|/method/user\\.sendMessengerOnlyPhoneConfirmationCode|/method/user\\.confirmMessengerOnlyPhone|/method/user\\.createMessengerOnlyAccount|/method/user\\.bypassLoginWithConfirmedMessengerCredentials|/method/user\\.prefillorautocompletecontactpoint|/method/user\\.validateregistrationdata|/method/user\\.register)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(.*-)?sonar6?([.-].*)?\\.fbcdn\\.net(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp)(?:\\?(?=.*_nc_nr=1.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(\\?.*)?$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:1997)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:9024)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:10537)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:11485)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:30808)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:40696)-2($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:1997)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:9024)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:10537)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:11485)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:30808)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net)(:?[0-9]{0,5})(.*(?:t[0-9]+\\.(?:40696)-2($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:fabb1-1|fabb1-2|fabv2-1|fabv2-2|flos1-1|flos1-2|flos5-1|flos5-2|flos5-3|fnbo2-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:f\\w+-\\w+)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:f\\w+-\\w+)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(\\?.*)?$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:1997)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:9024)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:10537)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:11485)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:30808)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:40696)-2($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:1997)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:9024)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:10537)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:11485)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:30808)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:40696)-2($|\\?.*$|/.*$)))",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:f\\w+-\\w+).fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(?:z-1-|z-m-|z-p3-|z-p4-)?([0-9a-zA-Z\\.-]+\\.)((?:f\\w+-\\w+).fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?:/fb_video|/messenger_video|/messenger_videos|/wa-msgr/mms/video)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?:/messenger_image|/fb_photo|/wa-msgr/mms/image)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?:/messenger_gif|/wa-msgr/mms/gif)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?:/messenger_audio|/wa-msgr/mms/ptt)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/messenger_file(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(?:z-m-|z-p3-|z-p4-)?(rupload)\\.?([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(\\w+)\\.(p|z)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp)(?:\\?(?=.*_nc_nr=1.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.webm|\\.m4v|\\.mpd)(\\?.*)?$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:1997)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:9024)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:10537)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:11485)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:30808)-6($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:40696)-2($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:1997)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:9024)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:10537)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:11485)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:8221|30361|30362)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:30808)-6($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*(?:t[0-9]+\\.(?:40696)-2($|\\?.*$|/.*$)))",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:0|8|9|10|12))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:0|8|9|10|12))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:0|8|9|10|12))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:1))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:1))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:1))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:2|26|27|28|29))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:2|26|27|28|29))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:2|26|27|28|29))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:4))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:4))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:4))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:6))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:6))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:6))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:21))($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:21))(/.*\\?.*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))(.*)(/t[0-9\\.]+-(?:21))(/[^\\?]*$)",
                                            "^(https?)://(z-1-|z-m-|z-p3-|z-p4-|)([0-9a-zA-Z\\.-]+)(\\.xx\\.fbcdn\\.net(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
                                            "^(https?)://(api|api2|z-m-api|api-read|z-p3-api|z-p4-api)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/me/message_audios(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/messagevideoattachment(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})((?://me/chunked_upload_sessions|//[0-9]+/chunks|/v2\\.3/[0-9]+/videos)(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/me/message_images(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/me/message_animated_images(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/me/message_files(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/me/photos(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(.*\\?.*$)",
                                            "^(https?)://(graph|graph2|z-m-graph|z-p3-graph|z-p4-graph)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})([^\\?]*$)",
                                            "^(https?)://(z-m-|z-1-|z-p3-|z-p4-)?(cdn|attachment|lookaside)\\.fbsbx\\.com(:?[0-9]{0,5})($|(?:/.*)?(?:\\?(?!.*_nc_ad=z-m.*$)(?=.*oh=.*$).*)$)",
                                            "^(https?)://(z-m-|z-1-|z-p3-|z-p4-)?(cdn|attachment|lookaside)\\.fbsbx\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(m|mobile|d|b-m)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})(/zero/toggle/settings/(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(free|m|mobile|d|b-m)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(www|web|z-m-www|b-www)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(upload|p-upload|z-upload|z-p3-upload|z-p4-upload)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(graph-video|z-graph-video|p-graph-video|z-p3-graph-video|z-p4-graph-video)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})($|\\?.*$|/.*$)",
                                            "^(https?)://(lookaside|z-m-lookaside|z-p3-lookaside|z-p4-lookaside)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(/assets(?:$|\\?.*$|/.*$))",
                                            "^(https?)://(lookaside|z-m-lookaside|z-p3-lookaside|z-p4-lookaside)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(/ras(?:$|\\?.*$|/.*$))",
                                        ],
                                        regex_replacer: [
                                            "$1://z-m-api.$3facebook.com$4$5",
                                            "$0",
                                            "$0",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://$2$3$4$6",
                                            "$1://z-m-$2$3$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://$2xx$4$6",
                                            "$1://z-m-$2xx$4$6",
                                            "$1://$2.$3facebook.com$4$5",
                                            "$1://z-m-$2.$3facebook.com$4$5",
                                            "$1://z-m-$2.$3facebook.com$4$5",
                                            "$1://z-m-$2.$3facebook.com$4$5",
                                            "$1://z-m-$2.$3facebook.com$4$5",
                                            "$1://z-m-$2.$3facebook.com$4$5",
                                            "$1://$2.z.$4facebook.com$5$6",
                                            "$0",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-$3$4$6",
                                            "$1://$3$4$6$7$8",
                                            "$1://z-m-$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8",
                                            "$1://z-m-$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8",
                                            "$1://$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8",
                                            "$1://z-m-$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8",
                                            "$1://z-m-$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8",
                                            "$1://$3$4$6$7$8&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3$4$6$7$8?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-$3$4$6",
                                            "$1://z-m-api.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5",
                                            "$1://graph.$3facebook.com$4$5",
                                            "$1://graph.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5",
                                            "$1://z-m-graph.$3facebook.com$4$5&_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://z-m-graph.$3facebook.com$4$5?_nc_eh=85a8bc67ae959cd21d464a0c665b37ce",
                                            "$1://$3.fbsbx.com$4$5",
                                            "$1://$3.fbsbx.com$4$5",
                                            "$1://m.$3facebook.com$4$5",
                                            "$1://m.$3facebook.com$4$5",
                                            "$1://www.$3facebook.com$4$5",
                                            "$1://z-upload.$3facebook.com$4$5",
                                            "$1://graph-video.$3facebook.com$4$5",
                                            "$1://z-m-lookaside.$3facebook.com$4",
                                            "$1://z-m-lookaside.$3facebook.com$4",
                                        ],
                                    },
                                ],
                            ],
                            ["ForgetPasswordAutoSearch", "addListenerForgetPasswordAutoSearch", [], ["m_login_email", "m_login_auto_search_form_contactpoint_hidden_input", "m_login_auto_search_form_forgot_password_button"]],
                            ["MLoginController", "initAccountRecoveryFunnelLogging", ["__elem_8a020238_0_0_Ep"], [{ __m: "__elem_8a020238_0_0_Ep" }, "click_forget_password", "QTxQZF6-Df-xOOwhT9z7CByy"]],
                            ["MGetInstalledRelatedApps", "logmTouchInstalledRelatedApps", [], ["apps_installed_login_view", "QTxQZF6-Df-xOOwhT9z7CByy"]],
                            ["BrowserPrefillLogging", "initContactpointFieldLogging", [], [{ contactpointFieldID: "m_login_email", serverPrefill: "+2347039448071" }]],
                            ["MHeaderTransparencyTooltip", "monitorTooltipBannerToggle", ["__elem_df6b4e4f_0_0_oy"], [{ __m: "__elem_df6b4e4f_0_0_oy" }, "login", 1080, "token_header"]],
                            ["BrowserPrefillLogging", "initPasswordFieldLogging", [], [{ passwordFieldID: "m_login_password" }]],
                            ["PlatformDialogCBTSetter", "setCBTInFormAndLog", ["__elem_921b58ef_0_0_9P"], [{ __m: "__elem_921b58ef_0_0_9P" }, "client_logged_out_init_impression"]],
                            ["MLoginView", "disableOnSubmit", ["__elem_921b58ef_0_0_9P", "__elem_7216e2ae_0_0_eT"], [{ __m: "__elem_921b58ef_0_0_9P" }, { __m: "__elem_7216e2ae_0_0_eT" }]],
                            ["MLoginController", "initRegButton", ["__elem_7216e2ae_0_1_Cz"], [{ root: { __m: "__elem_7216e2ae_0_1_Cz" }, regURI: "/reg-no-deeplink/?cid=103", useRegToLogin: true }]],
                            [
                                "MLoginController",
                                "initLoginForm",
                                ["__elem_de5177dd_0_0_++"],
                                [
                                    {
                                        root: { __m: "__elem_de5177dd_0_0_++" },
                                        ajaxURI: "/login/device-based/login/async/?refsrc=deprecated&lwv=101",
                                        clearOnDelete: false,
                                        listenKeyDown: false,
                                        isTwoStepsLogin: false,
                                        isActionLoggingEnabled: true,
                                        isCredsManagerEnabled: false,
                                        isCredsSavingEnabled: true,
                                        isPasswordlessEnabled: false,
                                        doNotShowUserHeader: false,
                                        shouldWaitForPasswordSave: false,
                                        onErrorRegURI: "/r.php",
                                        shouldAutoLandOnStep2: false,
                                        shouldPrefillJioHeaderForRegFromLogin: false,
                                        shouldProcessUserConsentForTokenHeader: false,
                                        shouldProcessUserConsentForHeader: true,
                                        shouldShowSmartLockSelector: false,
                                        shouldRunBotDetection: false,
                                        clearPrefillMaskOnKeydown: true,
                                        datrCookie: "QTxQZF6-Df-xOOwhT9z7CByy",
                                        pubKeyData: { publicKey: "e22468c9c62ced617ece73c1d0e58d9799ad3dd4c566cfaa17507cf9a61fcc62", keyId: 212 },
                                        shouldUseEmailDomainTypeahead: false,
                                        showDuoLikePasswordless: false,
                                        showSingleStepDuoLikePasswordless: false,
                                        trackingPreference: "install_from_passwordless_flow",
                                    },
                                ],
                            ],
                            [
                                "MPasswordPlainTextToggle",
                                "init",
                                ["__elem_e24cb174_0_0_su", "__elem_7216e2ae_0_2_8N", "__elem_e03291d5_0_0_NV", "__elem_e03291d5_0_1_YW"],
                                [{ __m: "__elem_e24cb174_0_0_su" }, { __m: "__elem_7216e2ae_0_2_8N" }, { __m: "__elem_e03291d5_0_0_NV" }, { __m: "__elem_e03291d5_0_1_YW" }],
                            ],
                            ["ServiceWorkerLoginAndLogoutListener", "listen", [], ["login_button_block", "login", "/sw?s=push", null]],
                            ["MBlockingTouchable", "init", ["__elem_e980dec4_0_0_gd"], [{ __m: "__elem_e980dec4_0_0_gd" }]],
                            ["KaiOSController", "maybeTagMeAsKaiOSApp", [], []],
                            ["MTouchable"],
                            ["AccessibilityWebVirtualCursorClickLogger", "init", ["__elem_49f6b607_0_0_Ow"], [[{ __m: "__elem_49f6b607_0_0_Ow" }]]],
                            ["GHLSurvey", "survey", [], []],
                            ["MScrollPositionSaver"],
                            ["InitMAjaxify"],
                            [
                                "MSeoDirectoryLinks",
                                "initLinks",
                                ["__elem_717bb1ae_0_0_yP", "__elem_ad2bcfb1_0_0_l8"],
                                [
                                    {
                                        visible: false,
                                        toggleButton: { __m: "__elem_717bb1ae_0_0_yP" },
                                        linksContainer: { __m: "__elem_ad2bcfb1_0_0_l8" },
                                        expandButton: { __m: "__elem_717bb1ae_0_0_yP" },
                                        collapseButton: { __m: "__elem_717bb1ae_0_0_yP" },
                                    },
                                ],
                            ],
                            ["MLogoutClearCache"],
                            [
                                "LoadingIndicator",
                                "init",
                                ["__elem_eed16c0a_0_0_4X", "__elem_a588f507_0_0_aP", "__elem_a588f507_0_1_4W"],
                                [{ __m: "__elem_eed16c0a_0_0_4X" }, { __m: "__elem_a588f507_0_0_aP" }, { __m: "__elem_a588f507_0_1_4W" }],
                            ],
                            ["MPageError"],
                            ["MPageHeaderAccessibility"],
                            ["MBlockingTouchable", "init", ["__elem_0cdc66ad_0_0_AE"], [{ __m: "__elem_0cdc66ad_0_0_AE" }]],
                            ["MBlockingTouchable", "init", ["__elem_0cdc66ad_0_1_B4"], [{ __m: "__elem_0cdc66ad_0_1_B4" }]],
                            ["MLoadingIndicator", "init", [], ["u_0_9_On"]],
                            ["LogHistoryListeners"],
                            ["ScriptPath", "set", [], ["/wap/index.php", "4e6eefd9", { imp_id: "0lPjgy6iW0pGAxvA5", ef_page: null }]],
                            ["MCommentViewportTracking", "singleton", [], [{ enabled: true, debug_console: false, debug_html: false, idle_timeout: 5000, min_duration_to_log: 100, min_visible_size: 200 }]],
                            ["MLogging", "main", [], [{ refid: 8 }]],
                            ["RemoteDevice", "init", [], [{ performHardwareDetection: false, hashId: null, vpd: false }]],
                            ["Artillery"],
                            ["MLinkHack"],
                            ["MModalDialogInit"],
                            ["MVerifyCache", "main", [], [{ viewer: 0 }]],
                            ["EventProfiler"],
                            ["MPageNavigationTracking", "init", [], []],
                            ["FalcoLoggerTransports", "attach", [], []],
                            ["ScriptPathLogger", "startLogging", [], []],
                            ["MTimeSpentBitArrayLogger", "init", [], ["m", false]],
                            [
                                "KaiOSController",
                                "init",
                                [],
                                [
                                    {
                                        __map: [
                                            ["app_id", null],
                                            ["should_log_app_version", true],
                                            [
                                                "fbt_strings",
                                                {
                                                    notif_action_open: "Open",
                                                    notif_action_update: "Update",
                                                    notif_action_dismiss: "Dismiss",
                                                    push_update_notif_title: "App update available",
                                                    push_update_notif_body: "Update your app now to keep getting instant updates from friends.",
                                                    update_alert: "Updating...",
                                                    update_completed_alert: "Update complete",
                                                },
                                            ],
                                            ["show_news_feed_on_notification_back", false],
                                            ["kaios__dev__", false],
                                            ["user_logged_in", false],
                                            ["in_latest_migration_phase", true],
                                            ["migration_group", "control_kite"],
                                            ["lid", "7242229531619620806"],
                                        ],
                                    },
                                ],
                            ],
                            ["MCoreDeferred"],
                            ["MqttLongPollingRunner"],
                            ["FbtLogging"],
                            ["IntlQtEventFalcoEvent"],
                            ["MPageControllerImpl"],
                            ["LogWebMemoryUsageFalcoEvent"],
                            ["TransportSelectingClientSingletonConditional"],
                            ["MPageFetcherImpl"],
                            ["json-bigint"],
                            [
                                "RequireDeferredReference",
                                "unblock",
                                [],
                                [
                                    ["MqttLongPollingRunner", "FbtLogging", "IntlQtEventFalcoEvent", "MPageControllerImpl", "LogWebMemoryUsageFalcoEvent", "TransportSelectingClientSingletonConditional", "MPageFetcherImpl", "json-bigint"],
                                    "sd",
                                ],
                            ],
                            [
                                "RequireDeferredReference",
                                "unblock",
                                [],
                                [
                                    ["MqttLongPollingRunner", "FbtLogging", "IntlQtEventFalcoEvent", "MPageControllerImpl", "LogWebMemoryUsageFalcoEvent", "TransportSelectingClientSingletonConditional", "MPageFetcherImpl", "json-bigint"],
                                    "css",
                                ],
                            ],
                        ],
                        pre_display_requires: [
                            ["AddressBar", "setupLoadListener", [], [], 4],
                            ["MobileBigPipeStratcomProxy", "init", [], [], 4],
                            ["Stratcom", "init", [], [], 4],
                            ["MViewport", "init", [], [], 4],
                            ["ViewportDimensions", "init", [], [], 4],
                            ["MPageController", "init", [], [], 4],
                            ["onSyncTTI", "run", [], [], 4],
                            ["MLiteInit", "init", [], [], 4],
                        ],
                    },
                    hsrp: {
                        hsdp: {
                            bxData: { "875231": { uri: "https://z-m-static.xx.fbcdn.net/rsrc.php/yD/r/d4ZIVX-5C-b.ico" } },
                            clpData: {
                                "2511": { r: 1, s: 1 },
                                "1744057": { r: 500, s: 1 },
                                "1744058": { r: 5000, s: 1 },
                                "1744059": { r: 10000, s: 1 },
                                "1744060": { r: 1000, s: 1 },
                                "1814852": { r: 1 },
                                "1838142": { r: 1, s: 1 },
                                "1744178": { r: 1, s: 1 },
                                "1942319": { r: 1, s: 1 },
                                "1842512": { r: 1 },
                                "1829319": { r: 1 },
                                "1829320": { r: 1 },
                                "1843988": { r: 1 },
                                "1848815": { r: 10000, s: 1 },
                                "1765264": { r: 1, s: 1 },
                            },
                            gkxData: {
                                "762": { result: false, hash: "AT7XePNdehhQhxt4pH4" },
                                "2795": { result: false, hash: "AT5ilL0A5sDVhuaBKBM" },
                                "3400": { result: false, hash: "AT5LV5sAIJng7-zcPb4" },
                                "6049": { result: false, hash: "AT58f153NfQ38W0Rc0c" },
                                "676837": { result: false, hash: "AT4N8wBZA8ctCdHwXRo" },
                                "778292": { result: false, hash: "AT574OhXHwX0kRP2C6k" },
                                "832242": { result: false, hash: "AT7QZmREZ7b0HQdOCUc" },
                                "945829": { result: true, hash: "AT6KFs8jy_GkmgnUT7c" },
                                "968609": { result: true, hash: "AT7nKteWCVYK6uN6R0c" },
                                "1001007": { result: false, hash: "AT54HpnriRBxXJ_MhoQ" },
                                "1066746": { result: false, hash: "AT55_E5b8Sj7u5rUy4I" },
                                "1166607": { result: false, hash: "AT7xrOkGBcaF8I5uIK4" },
                                "1167394": { result: false, hash: "AT7BpN-tlUPwbIIFyfA" },
                                "1393": { result: false, hash: "AT42aEHIHsK_NxGQy5g" },
                                "2772": { result: false, hash: "AT5Eu244WIce7iwqBuo" },
                                "3752": { result: false, hash: "AT6eS5UTkkMp_xbP0tw" },
                                "3820": { result: false, hash: "AT6sMf-XMjfPaRKvPNY" },
                                "3831": { result: false, hash: "AT4W23lQ0XxAZniMY2Q" },
                                "4075": { result: false, hash: "AT4_ZQi0sTjSt-RxK-Y" },
                                "8126": { result: false, hash: "AT4U7qG06p9sF6u8KKM" },
                                "676781": { result: false, hash: "AT4-DnA47xPbjtkwqhM" },
                                "712819": { result: false, hash: "AT79nTpb4gT-yu867iw" },
                                "1217157": { result: false, hash: "AT6B7YmllOsArnK6kG0" },
                                "1224637": { result: false, hash: "AT7JRluWxuwDm3XzxTI" },
                                "1554827": { result: false, hash: "AT7zueGLhGo0cT5xM9c" },
                                "1738486": { result: false, hash: "AT4cX37oQco6DwhULXU" },
                                "6734": { result: false, hash: "AT6OQ83_QdFAwGYH22g" },
                                "910664": { result: false, hash: "AT69YyFAmMObhORGXWc" },
                                "1511920": { result: false, hash: "AT6pY2ROWoYnl3_cIO4" },
                                "1059877": { result: false, hash: "AT53XV4TWT4lc3_m6Oc" },
                                "7534": { result: false, hash: "AT79UgwazyQmKjdFyzI" },
                                "676811": { result: false, hash: "AT4zC0IqvJCbKsUei1k" },
                                "820050": { result: true, hash: "AT7bjlcFFlowDw-S1D4" },
                                "148": { result: false, hash: "AT5V6Me6WVwsRI3wYRc" },
                                "5525": { result: false, hash: "AT56gpXxsmc6rAjxJDQ" },
                                "5689": { result: true, hash: "AT5NXMhVv9ZyYGZgSS8" },
                                "2223": { result: false, hash: "AT4s3JaAt9nQ6ucmsX8" },
                                "2341": { result: false, hash: "AT7nNd913_uqf_cR8rU" },
                                "862436": { result: false, hash: "AT7YsAcWL8-1WZrO6Dk" },
                                "3499": { result: false, hash: "AT5l5tI3kdeSuUxUqrw" },
                            },
                            qexData: { "37": { r: null }, "130": { r: null }, "131": { r: null }, "656": { r: null }, "657": { r: null }, "660": { r: null }, "27": { r: null }, "91": { r: null }, "123": { r: null } },
                            qplData: { "891": { r: 1 } },
                        },
                        hblp: {
                            consistency: { rev: 1007643455 },
                            rsrcMap: {
                                "6qUA1gl": { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yU/r/eF7rJW3DDe6.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                VvVFw8n: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yn/r/AWepvf-vdZG.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                hZeK99e: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yv/r/rkrWr3j_Q-m.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                PDQbV7k: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3i58q4/yp/l/en_GB/wH4Pyce9QpG.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                Gd5GBLJ: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yc/r/5l2myezNNYd.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                PHSDjJd: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yg/r/PECKzj5A_K4.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                "PBV/XJX": { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3i3kA4/y6/l/en_GB/KfoTJ0mZiri.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                "1fb7syx": { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yr/r/BGG8HnPJb24.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                Vu5ymAz: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yO/r/f0ZKzQ8KhtR.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                tUjj10Y: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/y6/r/Fh7vli0vbit.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                fVaBgHx: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/y3/r/ENNZJttsiwM.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                "o/jYUaG": { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3iLl54/yw/l/en_GB/0D75Vw0sOuD.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                iqaNd7v: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/y9/r/0sm6BuV2M9-.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                WlqnTfs: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yr/r/x7HbE6mrjoY.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                            },
                            compMap: {
                                ODS: { r: ["6qUA1gl"], be: 1 },
                                QPLInspector: { r: ["VvVFw8n"], be: 1 },
                                Cookie: { r: ["6qUA1gl"], be: 1 },
                                WebSpeedInteractionsTypedLogger: { r: ["6qUA1gl", "iqaNd7v", "Gd5GBLJ", "hZeK99e"], rds: { m: ["FbtLogging", "IntlQtEventFalcoEvent"] }, be: 1 },
                                PerfXSharedFields: { r: ["PDQbV7k", "6qUA1gl"], be: 1 },
                            },
                        },
                    },
                    allResources: ["VC6Dj0h", "DvIsx5X", "6qUA1gl", "lUg7w0b", "hZeK99e", "PDQbV7k", "M7ZJk4o", "pDmmboz", "Gd5GBLJ", "PHSDjJd", "PBV/XJX", "1fb7syx", "Vu5ymAz", "tUjj10Y", "fVaBgHx", "o/jYUaG", "WlqnTfs"],
                });
            });