            requireLazy(["__bigPipe"], function (bigPipe) {
                bigPipe.onPageletArrive({
                    id: "last_response",
                    phase: 63,
                    last_in_phase: true,
                    the_end: true,
                    jsmods: {
                        define: [
                            ["ChannelClientConfig", [], {}, 395],
                            ["MercuryConfig", [], {}, 35],
                            [
                                "MqttWebConfig",
                                [],
                                {
                                    fbid: "0",
                                    appID: 219994525426954,
                                    endpoint: "wss://edge-chat.facebook.com/chat",
                                    pollingEndpoint: "https://edge-chat.facebook.com/mqtt/pull",
                                    subscribedTopics: [],
                                    capabilities: 10,
                                    clientCapabilities: 3,
                                    chatVisibility: false,
                                    hostNameOverride: "",
                                },
                                3790,
                            ],
                            ["MqttPublishTimeoutConfig", [], { mqttPublishTimeoutMs: 90000 }, 4266],
                            [
                                "MobileWebMessageTypesSitevarConfig",
                                [],
                                {
                                    ChatProxySupportedMessageTypes: {
                                        __map: [
                                            ["anbox", true],
                                            ["chatproxy-presence", true],
                                            ["confirm_contactpoint", true],
                                            ["delta", true],
                                            ["deltaflow", true],
                                            ["deltaflowreject", true],
                                            ["friend_requests_seen", true],
                                            ["friending_state_change", true],
                                            ["inbox", true],
                                            ["jewel_friending_notifs", true],
                                            ["jewel_requests_add", true],
                                            ["jewel_requests_remove_old", true],
                                            ["live_poke", true],
                                            ["m_notification", true],
                                            ["mobile_requests_count", true],
                                            ["nav_update_counts", true],
                                            ["notifications_read", true],
                                            ["notifications_seen", true],
                                            ["onevc", true],
                                            ["privacy_changed", true],
                                            ["qprimer", true],
                                            ["skywalker", true],
                                            ["typ", true],
                                            ["webrtc", true],
                                        ],
                                    },
                                    MQTTMigrationExcludeMessageTypes: {
                                        __map: [
                                            ["anbox", true],
                                            ["chatproxy-presence", true],
                                            ["delta", true],
                                            ["deltaflow", true],
                                            ["deltaflowreject", true],
                                            ["onevc", true],
                                            ["qprimer", true],
                                            ["skywalker", true],
                                            ["typ", true],
                                            ["webrtc", true],
                                        ],
                                    },
                                },
                                4273,
                            ],
                            ["MqttWebDeviceID", [], { clientID: "c0af2bc6-1b37-497a-a93e-4f6f71e80f6b" }, 5003],
                            ["IntlCurrentLocale", [], { code: "en_GB" }, 5954],
                            ["MLoginTopDomainsConfig", [], { topEmailDomains: ["gmail.com", "yahoo.com", "outlook.com", "yandex.com", "naij.com"] }, 6972],
                            ["USIDMetadata", [], { browser_id: "?", tab_id: "", page_id: "Prvxe8z161i6oe", transition_id: 0, version: 6 }, 5888],
                            ["BrowserPaymentHandlerConfig", [], { enabled: false }, 3904],
                            ["BrowserPushPubKey", [], { appServerKey: "BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjFNkuTq9j4MPAVLvAFhXrUU1A9UxyxBA7YIOjqDIDHI" }, 4806],
                            ["MTouchableSyntheticClickGK", [], { USE_SYNTHETIC_CLICK: true }, 368],
                            ["cr:686", [], { __rc: [null, "Aa1qUz1vxwgtxTLEtPr-p1IpOvUxGsBoOykel8D-A_J-WtE5UbG_xi27m8LMRZgSMrtBnZiHawiINoKvUiM7Mz0qWQ"] }, -1],
                            ["cr:1069930", [], { __rc: [null, "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:1083116", ["XAsyncRequest"], { __rc: ["XAsyncRequest", "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:1083117", [], { __rc: [null, "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:1984081", [], { __rc: [null, "Aa2v0pZYTpyV1uitzuMMsM-cWg7v0aWO6S2wy5dcfiU1IDsESNeqsRDr0tscp--f6zMQ4KyTTqSQlwot89j9DYmUvEVz"] }, -1],
                            ["cr:334", ["ghlTestUBTFacebook"], { __rc: ["ghlTestUBTFacebook", "Aa0zx_r4ZzulFIb8yh7Cq7bhVTj1rkJVqZHZdcxBFFOsc9bog-pKp0J0fRwTHZlnKbDcjFlY8A-L_VHuBlzmYXP6_Q"] }, -1],
                            ["cr:1088657", [], { __rc: [null, "Aa1RPbgnQGKP2PaR4wsmuiRdy8arT0a-Y5lmwjtCUpJea58WIfiF524Ovlsbg9P1EQ0cxVuNriLabsg5FOOej3E"] }, -1],
                            ["cr:1543261", [], { __rc: [null, "Aa3KFLf9il78njfIlOHxR_sxER3Xo4FWxBSoJR2kMCQpTcVxucgOuZdw4GzGUkBTYKPXaPQLfHJUBZYgDB3NjTSo"] }, -1],
                            ["cr:708886", ["EventProfilerImpl"], { __rc: ["EventProfilerImpl", "Aa2inky824v2_fUpjbABFOpt3MnF-4QbqfjgzWeW1tGEvp7ou23v1oSdiEis4O5hra1uLo-6ygZh4e0hYUyIRFoJ38k"] }, -1],
                            ["cr:1094907", [], { __rc: [null, "Aa36EkLGg-AjsXbqwJObuUZvpmLQD2-oZzPf6o_MQWkjwwPKbWjq72PN9qPLAPMMEKpZgek28tCI4ICMNuVDgcU"] }, -1],
                            ["cr:5800", [], { __rc: [null, "Aa0xrLAkV6brsOEmObMijySD0wN3Wsq3Ddj_MEuA1PrPOKZ_vPkIs8G3tfPCLfOeN_f-M8IJ7v-Tw0dGbaCQlHWz_Do"] }, -1],
                            ["GhlTennisKnobsConfig", [], { ghlbox_log_validity_in_mins: 7200, ghlbox_initialize_in_mins: 14400, change_class_interval_in_mins: 1440 }, 6687],
                            [
                                "EventConfig",
                                [],
                                {
                                    sampling: {
                                        bandwidth: 0,
                                        play: 0,
                                        playing: 0,
                                        progress: 0,
                                        pause: 0,
                                        ended: 0,
                                        seeked: 0,
                                        seeking: 0,
                                        waiting: 0,
                                        loadedmetadata: 0,
                                        canplay: 0,
                                        selectionchange: 0,
                                        change: 0,
                                        timeupdate: 0,
                                        adaptation: 0,
                                        focus: 0,
                                        blur: 0,
                                        load: 0,
                                        error: 0,
                                        message: 0,
                                        abort: 0,
                                        storage: 0,
                                        scroll: 200000,
                                        mousemove: 20000,
                                        mouseover: 10000,
                                        mouseout: 10000,
                                        mousewheel: 1,
                                        MSPointerMove: 10000,
                                        keydown: 0.1,
                                        click: 0.02,
                                        mouseup: 0.02,
                                        __100ms: 0.001,
                                        __default: 5000,
                                        __min: 100,
                                        __interactionDefault: 200,
                                        __eventDefault: 100000,
                                    },
                                    page_sampling_boost: 1,
                                    interaction_regexes: {},
                                    interaction_boost: {},
                                    event_types: {},
                                    manual_instrumentation: false,
                                    profile_eager_execution: false,
                                    disable_heuristic: true,
                                    disable_event_profiler: false,
                                },
                                1726,
                            ],
                            ["MarauderConfig", [], { app_version: "1.0.0.0 (1007643455)", gk_enabled: false }, 31],
                            [
                                "SearchMTouchGlobalOptions",
                                [],
                                {
                                    enableSeeMore: true,
                                    enableQueryThrottle: true,
                                    queryThrottleTime: 125,
                                    queryWaitTime: 125,
                                    enableEagerSendRequest: true,
                                    useBanzaiLogging: false,
                                    redirectPages: false,
                                    noSnippet: false,
                                    defaultNumTopResultsToShow: 3,
                                    useNewTypeaheadPerfLogger: true,
                                    keywordsOnlyEnabled: true,
                                    prefixMatchEntityBootstrap: true,
                                    disableHighlighting: false,
                                },
                                344,
                            ],
                            [
                                "TimeSliceInteractionSV",
                                [],
                                {
                                    on_demand_reference_counting: true,
                                    on_demand_profiling_counters: true,
                                    default_rate: 1000,
                                    lite_default_rate: 100,
                                    interaction_to_lite_coinflip: { ADS_INTERFACES_INTERACTION: 0, ads_perf_scenario: 0, ads_wait_time: 0, Event: 10 },
                                    interaction_to_coinflip: { ADS_INTERFACES_INTERACTION: 1, ads_perf_scenario: 1, ads_wait_time: 1, Event: 500 },
                                    enable_heartbeat: true,
                                    maxBlockMergeDuration: 0,
                                    maxBlockMergeDistance: 0,
                                    enable_banzai_stream: true,
                                    user_timing_coinflip: 50,
                                    banzai_stream_coinflip: 0,
                                    compression_enabled: true,
                                    ref_counting_fix: false,
                                    ref_counting_cont_fix: false,
                                    also_record_new_timeslice_format: false,
                                    force_async_request_tracing_on: false,
                                },
                                2609,
                            ],
                            ["MBootstrapCacheMaxCacheTime", [], { maxCacheTimeByKey: { typeahead_facebar3: 1209600000, typeahead_search_bem3: 1209600000 } }, 2886],
                            [
                                "MSearchTypeaheadConfig",
                                [],
                                {
                                    sources: {
                                        bootstrapped: { src: "/typeahead/search/facebar/bootstrap/?filters%5B0%5D=keyword", source_key: "facebar3", max_results: 6 },
                                        nullstate: { src: "/typeahead/search/facebar/nullstate/", max_results: 20 },
                                        online: { src: "/typeahead/search/facebar/query/?context=facebar&grammar_version=bee09f93fa732cfa59a1cb6d9f450d3892424e49&viewer=0&rsp=search", max_results: 20, enable_caching: true },
                                    },
                                    typeaheadScubaInfo: null,
                                    disableLongerQueryCacheHit: true,
                                    compositeSourceConfig: {
                                        maxResults: 50,
                                        minCostForUserToSurfaceAtTop: 7,
                                        maxPositionOfEntityToDivideKeywords: 5,
                                        maxKeywordAboveEntities: 2,
                                        filterOutTypes: [],
                                        keepBootstrapped: true,
                                        enableLegacyStyleBucketization: true,
                                    },
                                    hasRecentSearches: false,
                                    numResultsToFetch: 13,
                                    initialNumRecentResultsToShow: 13,
                                    defaultNumTopResultsToShow: 3,
                                    keywordsOnlyEnabled: true,
                                    keywordBucketSize: 6,
                                },
                                4113,
                            ],
                        ],
                        require: [
                            [
                                "BDClientSignalCollectionTrigger",
                                "startSignalCollection",
                                [],
                                [
                                    {
                                        sc:
                                            '{"t":1659080345,"c":[[30000,838801],[30001,838801],[30002,838801],[30003,838801],[30004,838801],[30005,838801],[30006,573585],[30007,838801],[30008,838801],[30012,838801],[30013,838801],[30015,806033],[30018,806033],[30021,540823],[30022,540817],[30040,806033],[30093,806033],[30094,806033],[30095,806033],[30101,541591],[30102,541591],[30103,541591],[30104,541591],[30106,806039],[30107,806039],[38000,541427],[38001,806643]]}',
                                        fds: 60,
                                        fda: 60,
                                        i: 60,
                                        sbs: 1,
                                        dbs: 100,
                                        bbs: 100,
                                        hbi: 60,
                                        rt: 262144,
                                        hbcbc: 2,
                                        hbvbc: 0,
                                        hbbi: 30,
                                        sid: -1,
                                        hbv: "3302201742167082184",
                                    },
                                ],
                            ],
                            [
                                "NavigationMetrics",
                                "setPage",
                                [],
                                [
                                    {
                                        page: "/wap/index.php",
                                        page_type: "normal",
                                        page_uri:
                                            "https://m.facebook.com/?wtsid=rdr_004eWgEbxSX4fxdn6&rtime=1686212920&subno_key=AaHM5ULBceZluvLHxanHBOx_zTkKxwGc7lGmGRoZ2jiTqZV6hr4Oe2Fu-UpIq8uxXfKJO--SNsU5KdaD410GkJJ8URfNUUAazQEfYwmMwV3hhJGgzXwJPQ-J3-E1oWcctqJwhOWpQP8k_qev4aYqLS4yQlodddOVFMelG8fQ-jleb-FDxfk5tflCGmA2zCqSn9b5WdfWjYH-5YecLqYV64Ktn70caIuEriyH6pAs3pBVvNZT1rI8tiCC-n6LNB7OILTsNi8I8JwiIWXvjfV2fFwxEOvEA3w0eE90DRGaFCauWeRSa5ZMB8i9e_INI6ySK-A&hrc=1&refsrc=deprecated&_rdr",
                                        serverLID: "7242229531619620806",
                                    },
                                ],
                            ],
                            ["ServiceWorkerURLCleaner", "removeRedirectID", [], []],
                        ],
                    },
                    hsrp: {
                        hsdp: { clpData: { "1743095": { r: 1, s: 1 } }, gkxData: { "1652843": { result: false, hash: "AT6uh9NWRY4QEQoY_cA" } } },
                        hblp: { consistency: { rev: 1007643455 }, rsrcMap: { zPYlTyl: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yO/r/_tJ17sGyxOX.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 } } },
                    },
                    allResources: ["UIx9zkZ", "hZeK99e", "6qUA1gl", "zPYlTyl"],
                });
            });
    